spring.application.name=e-commerce

spring.datasource.url=jdbc:postgresql://localhost:5432/ecommerce?useSSL=false&serverTimezone=Asia/Ho_Chi_Minh&useLegacyDatetimeCode=false&allowPublicKeyRetrieval=true
spring.datasource.username=postgres
spring.datasource.password=Haovip1!

spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.connection.characterEncoding=UTF-8

# Cau hinh log
logging.level.org.springframework.security=DEBUG

#Hien thi cau lenh sql
spring.jpa.show-sql=true
#Fomat cau lenh
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.hibernate.ddl-auto=update



# API version
server.servlet.context-path=${SERVER_SERVLET_CONTEXT_PATH}

# JWT
jwt.access-token.secret=${JWT_ACCESS_TOKEN_SECRET}
jwt.access-token.expiration=${JWT_ACCESS_TOKEN_EXPIRATION}
jwt.refresh-token.expiration=${JWT_REFRESH_TOKEN_EXPIRATION}

# Time token
token.email-verification.expiration-minutes=${TOKEN_EMAIL_VERIFICATION_EXPIRATION_MINUTES}
token.refresh.expiration-days=${TOKEN_REFRESH_EXPIRATION_DAYS}

# Cloudinary
cloudinary.cloud_name=${CLOUDINARY_CLOUD_NAME}
cloudinary.api_key=${CLOUDINARY_API_KEY}
cloudinary.api_secret=${CLOUDINARY_API_SECRET}
cloudinary.folder=${CLOUDINARY_FOLDER}

# Upload

spring.servlet.multipart.max-file-size=10MB
# Gi?i h?n 10MB cho to�n request
spring.servlet.multipart.max-request-size=10MB

# VNPay
vnpay.tmnCode=${VNPAY_TMNCODE}
vnpay.secretKey=${VNPAY_SECRET_KEY}
vnpay.url=${VNPAY_URL}
vnpay.returnUrl=${VNPAY_RETURN_URL}
vnpay.version=${VNPAY_VERSION}
vnpay.command=${VNPAY_COMMAND}
vnpay.currCode=${VNPAY_CURRCODE}
vnpay.orderType=${VNPAY_ORDER_TYPE}

# Email
spring.mail.host=${EMAIL_HOST}
spring.mail.port=${EMAIL_PORT}
spring.mail.username=${EMAIL_USERNAME}
spring.mail.password=${EMAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=${EMAIL_PROPERTIES_MAIL_SMTP_AUTH}
spring.mail.properties.mail.smtp.starttls.enable=${EMAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE}

#Redis
spring.data.redis.host=${REDIS_HOST}
spring.data.redis.port=${REDIS_PORT}
spring.data.redis.password=${REDIS_PASSWORD}
spring.data.redis.database=${REDIS_DATABASE}
spring.data.redis.timeout=${REDIS_TIMEOUT}

spring.data.redis.lettuce.pool.max-active=${REDIS_POOL_MAX_ACTIVE}
spring.data.redis.lettuce.pool.max-idle=${REDIS_POOL_MAX_IDLE}
spring.data.redis.lettuce.pool.min-idle=${REDIS_POOL_MIN_IDLE}

#Redis key
spring.redis.key-prefix=${REDIS_KEY_PREFIX}

#Otp
spring.otp.expiration-minutes=${OTP_EXPIRATION_MINUTES}
spring.otp.length=${OTP_LENGTH}
spring.otp.max-attempts=${OTP_MAX_ATTEMPTS}
spring.otp.attempt-expiry-minutes=${OTP_ATTEMPT_EXPIRY_MINUTES}

#Ratelimit
ratelimit.otp.per-minute=${RATELIMIT_OTP_PER_MINUTE}
ratelimit.otp.per-hour=${RATELIMIT_OTP_PER_HOUR}

#Login attempt
login.max-attempts=${LOGIN_MAX_ATTEMPTS}
login.attempt-expiry-minutes=${LOGIN_ATTEMPT_EXPIRY_MINUTES}
login.lock-duration-minutes=${LOGIN_LOCK_DURATION_MINUTES}

# spring.config.import=optional:file:./local.env
# spring.application.name=e-commerce

# spring.datasource.url=jdbc:postgresql://localhost:5432/ecommerce?useSSL=false&serverTimezone=Asia/Ho_Chi_Minh&useLegacyDatetimeCode=false&allowPublicKeyRetrieval=true
# spring.datasource.username=postgres
# spring.datasource.password=Haovip1!

# spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect
# spring.jpa.properties.hibernate.connection.characterEncoding=UTF-8

# # Cau hinh log
# logging.level.org.springframework.security=DEBUG

# #Hien thi cau lenh sql
# spring.jpa.show-sql=true
# #Fomat cau lenh
# spring.jpa.properties.hibernate.format_sql=true

# spring.jpa.hibernate.ddl-auto=update



# # API version
# server.servlet.context-path=/api/v1

# # JWT
# jwt.access-token.secret=843567893696976453275974432697R634976R738467TR678T34865R6834R8763T478378637664538745673865783678548735687R3
# jwt.access-token.expiration=604800000
# jwt.refresh-token.expiration=604800000

# # Time token
# token.email-verification.expiration-minutes=5
# token.refresh.expiration-days=7

# # Cloudinary
# cloudinary.cloud_name=dgmi3soo9
# cloudinary.api_key=832834795868786
# cloudinary.api_secret=p8z8nXGm8Ekkr27dm-psgs6hVn4
# cloudinary.folder=Ecommerce

# # Upload

# spring.servlet.multipart.max-file-size=10MB
# # Gi?i h?n 10MB cho to�n request
# spring.servlet.multipart.max-request-size=10MB

# # VNPay
# vnpay.tmnCode=K7AYB02L
# vnpay.secretKey=1HW1K1ESUB4RQBNACCDRWXAY1G8AVO99
# vnpay.url=https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
# vnpay.returnUrl=http://127.0.0.1:5500/result.html
# vnpay.version=2.1.0
# vnpay.command=pay
# vnpay.currCode=VND
# vnpay.orderType=other

# # Email
# spring.mail.host=smtp.gmail.com
# spring.mail.port=587
# spring.mail.username=kien06112004@gmail.com
# spring.mail.password=mlse ocra cmjp srsm
# spring.mail.properties.mail.smtp.auth=true
# spring.mail.properties.mail.smtp.starttls.enable=true

# #Redis
# spring.data.redis.host=localhost
# spring.data.redis.port=6379
# spring.data.redis.password=
# spring.data.redis.database=0
# spring.data.redis.timeout=3000ms

# spring.data.redis.lettuce.pool.max-active=8
# spring.data.redis.lettuce.pool.max-idle=4
# spring.data.redis.lettuce.pool.min-idle=1

# #Redis key
# spring.redis.key-prefix=ecommerce

# #Otp
# spring.otp.expiration-minutes=5
# spring.otp.length=6
# spring.otp.max-attempts=5
# spring.otp.attempt-expiry-minutes=15

# #Ratelimit
# ratelimit.otp.per-minute=5
# ratelimit.otp.per-hour=20

# #Login attempt
# login.max-attempts=5
# login.attempt-expiry-minutes=15
# login.lock-duration-minutes=30