spring.application.name=e-commerce

spring.datasource.url=jdbc:postgresql://localhost:5432/ecommerce?useSSL=false&serverTimezone=Asia/Ho_Chi_Minh&useLegacyDatetimeCode=false&allowPublicKeyRetrieval=true
spring.datasource.username=postgres
spring.datasource.password=Kien04112004!

spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.connection.characterEncoding=UTF-8

logging.level.org.springframework.security=DEBUG

#Hien thi cau lenh sql
spring.jpa.show-sql=true
#Fomat cau lenh
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.hibernate.ddl-auto=update

# Api version
server.servlet.context-path=/api/v1

# JWT
jwt.access-token.secret=843567893696976453275974432697R634976R738467TR678T34865R6834R8763T478378637664538745673865783678548735687R3
jwt.access-token.expiration=604800000
jwt.refresh-token.expiration=604800000

# Cloud
cloudinary.cloud_name = dgmi3soo9
cloudinary.api_key = 832834795868786
cloudinary.api_secret = p8z8nXGm8Ekkr27dm-psgs6hVn4
cloudinary.folder: Ecommerce

# Gi?i h?n kích th??c file upload
spring.servlet.multipart.max-file-size=10MB
# Gi?i h?n 10MB cho toàn request
spring.servlet.multipart.max-request-size=10MB

# VNPay
vnpay.tmnCode=K7AYB02L
vnpay.secretKey=1HW1K1ESUB4RQBNACCDRWXAY1G8AVO99
vnpay.url=https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
vnpay.returnUrl=http://127.0.0.1:5500/result.html
vnpay.version=2.1.0
vnpay.command=pay
vnpay.currCode=VND
vnpay.orderType=other

server.port=8080
server.address=0.0.0.0
